# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Parser-Pretty
version:      0.01
version_from: lib/Template/Parser/Pretty.pm
installdirs:  site
requires:
    Template::Parser:              2.82
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
